# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71f7f4b6bec97bc8133a91865c66a051c433c8a2e1a987558c14c84801ccd590ade293bfa699cbda0f8908400bfb1a5cca700ae789f12df722710233c831b7f6

test:
  secret_key_base: 30fb7af44c3db89b32714ff5ed049db1879ce50da0c90f8695fa68f2dbb9a4c856b0144f8ece0828fe276b8efc718071b2ad258548d9e2f37d5127845be0d5b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
